networks:
  network:
    driver: bridge
    
volumes:
  postgres_data:

services:
    
  api:
    container_name: TicTacToeAPI
    image: tictactoe.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5000
    env_file:
      - game.env
    build:
      context: .
      dockerfile: TicTacToeApp.API/Dockerfile
    ports:
      - "8080:5000"
    networks:
      - network
    depends_on:
      - db
      
  db:
    image: postgres:latest
    container_name: TicTacToeAppPostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: TicTacToeAppDatabase
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network
