version: '3.8'

networks:
  network:
    driver: bridge

volumes:
  postgres_data:

services:
  api:
    container_name: TicTacToeAPI
    image: tictactoe.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5000
    env_file:
      - game.env
    build:
      context: .
      dockerfile: TicTacToeApp.API/Dockerfile
    ports:
      - "8080:5000"
    networks:
      - network
    depends_on:
      db:
        condition: service_healthy  # ⚠️ Ждём, пока БД не станет healthy

  db:
    image: postgres:latest
    container_name: TicTacToeAppPostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: TicTacToeAppDatabase
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network