@api = http://localhost:5055/api

### Показать все игры 

GET {{api}}/games
Accept: application/json

### Получить отдельную игру

@gameId = 15c63203-c5c3-42be-b9b1-c7523d53a37c

GET {{api}}/games/{{gameId}}
Accept: application/json

### Создать игру

POST {{api}}/game/new
Accept: application/json

### Сделать ход X или O

POST {{api}}/game/{{gameId}}/move
Content-Type: application/json

{
  "x": 1,
  "y": 2,
  "p": "X"
}