# This is a generated file. Not intended for manual editing.
services:
  api:
    build:
      context: "C:\\Users\\asv\\Desktop\\TicTacToeApp"
      dockerfile: "TicTacToeApp.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/TicTacToeApp.API.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "tictactoe.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\asv\\Desktop\\TicTacToeApp\\TicTacToeApp.API:/app:rw"
    - "C:\\Users\\asv\\Desktop\\TicTacToeApp:/src:rw"
    - "C:\\Users\\asv\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
